<?php
$this->headScript()->appendFile($this->assetUrl('js/dspace-connector.js', 'DspaceConnector'));
$this->headLink()->appendStylesheet($this->assetUrl('css/dspace-connector.css', 'DspaceConnector'));
$form->prepare(); 
$escapeHtml = $this->plugin('escapeHtml');
$formElement = $this->plugin('formElement');
$formLabel = $this->plugin('formLabel');
?>

<h1><?php echo $escapeHtml($this->translate('DSpace Connector')); ?></h1>
<div id="import" class="section active">
    <?php echo $this->form()->openTag($form); ?>
    <fieldset id='page-actions'>
        <button><?php echo $this->translate("Get Collections And Communities"); ?></button>
    </fieldset>
    <?php $apiElement = $form->get('api_url'); ?>
    <?php echo $this->formRow($apiElement) ; ?>
    <?php echo $this->formElementErrors($apiElement, array('class' => 'messages')); ?>
    <?php echo $formElement($form->get('csrf')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
