<?php
$this->htmlElement('body')->appendAttribute('class', 'dspace jobs undo');
$escape = $this->plugin('escapeHtml');
?>

<h1><?php echo $escape($this->translate('Past DSpace Imports')); ?></h1>
<?php echo $this->pagination(); ?>

<form method='POST'>
    <fieldset id='page-actions'>
        <input type='submit' value='Submit' />
    </fieldset>
    <table>
        <thead>
            <tr>
                <th><?php echo $escape($this->translate('Undo?'));?></th>
                <th><?php echo $this->sortLink($this->translate('Job ID'), 'id');?></th>
                <th><?php echo $escape($this->translate('Dspace Collection Link'));?></th>
                <th><?php echo $escape($this->translate('Date'));?></th>
                <th><?php echo $escape($this->translate('Status'));?></th>
                <th><?php echo $escape($this->translate('Owner'));?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($jobs as $job): ?>
        <tr>
            <td><input type='checkbox' name='jobs[]' value='<?php echo $job->id(); ?>' />
            <td><?php echo $job->id(); ?></td>
            <td>
                <?php $args = $job->args();
                echo $args['collection_link'];
                ?>
            </td>
            <td><?php echo $escape($this->i18n()->dateFormat($job->started())); ?></td>
            <td><?php echo $job->status(); ?></td>
            <td><?php echo $this->hyperlink($job->owner()->username(), $this->url('admin/id', array('controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()))); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
