<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/dspace-connector.css', 'DspaceConnector'));
$this->htmlElement('body')->appendAttribute('class', 'dspace jobs undo browse');
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Dspace Connector'), 1, $this->translate('Past Imports')); ?>

<?php if(empty($imports)): ?>

<?php else: ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->browse()->renderSortSelector('dspace_past_imports'); ?>
</div>
<form method='POST'>
    <fieldset id='page-actions'>
        <input type='submit' value='Submit' />
    </fieldset>

    <table class="tablesaw" data-tablesaw-mode="stack" aria-label="<?php echo $this->translate('Past Imports'); ?>">
        <thead>
            <tr>
                <th scope="col"><?php echo $this->translate('Job ID'); ?></th>
                <th scope="col"><?php echo $escape($this->translate('Actions'));?></th>
                <th><?php echo $escape($this->translate('Dspace collection'));?></th>
                <th><?php echo $escape($this->translate('Comment'));?></th>
                <th><?php echo $escape($this->translate('Items'));?></th>
                <th><?php echo $escape($this->translate('Date'));?></th>
                <th><?php echo $escape($this->translate('Status'));?></th>
                <th><?php echo $escape($this->translate('Owner'));?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($imports as $import): ?>
        <?php $job = $import->job(); ?>
        <?php $undoJob = $import->undoJob(); ?>
        <?php $disableOption = ($job->jobClass() == 'ArchivesspaceConnector\Job\Undo') ? 'disabled' : ''; ?>
        <?php $rerunJob = $import->rerunJob(); ?>
        <tr>
            <th scope="row"><?php echo $job->link($job->id()); ?></th>
            <td>
            <div class="dspace-connector-inputs" role="radiogroup" aria-label="<?php echo $this->translate('Action options'); ?>">
                <label>
                    <input type='radio' name='jobActions[<?php echo $job->id(); ?>]' value checked aria-label="<?php echo $this->translate('[No Action]'); ?>" />
                    <?php echo $this->translate('[No Action]'); ?>
                </label>
                <label>
                    <input type='radio' name='jobActions[<?php echo $job->id(); ?>]' value='undo' aria-label="<?php echo $this->translate('Undo'); ?>" <?php echo $disableOption; ?> />
                    <?php echo $this->translate('Undo'); ?>
                </label>
                <label>
                    <input type='radio' name='jobActions[<?php echo $job->id(); ?>]' value='rerun' aria-label="<?php echo $this->translate('Re-run'); ?>" <?php echo $disableOption; ?> />
                    <?php echo $this->translate('Re-run'); ?>
                </label>
            </div>
            </td>
            <td>
                <?php
                $args = $job->args();
                $linkText = isset($args['collection_name']) ? $args['collection_name'] : $this->translate('collection link');
                if (isset($args['newAPI']) && (bool) $args['newAPI'] === TRUE) {
                    echo $this->hyperlink($linkText, $args['collection_link'], ['target' => '_blank']);
                } else {
                    echo $this->hyperlink($linkText, $args['api_url'] . $args['collection_link'], ['target' => '_blank']);
                }
                ?>
            </td>
            <td class="dspace-comment">
                <?php echo $import->comment(); ?>
            </td>
            <td>
                <?php
                $linkID = $job->id();
                $totalCount = $import->addedCount() + $import->updatedCount();
                // Only link to search results for Job IDs with associated items
                $totalResults = $this->api()->search('items', ['dspace_import_id' => $linkID]);
                if ($totalResults->getTotalResults() > 0) {
                    echo $this->hyperlink('Total: ' . $totalResults->getTotalResults(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['dspace_import_id' => $linkID]]), ['target' => '_blank']) . '<br>';
                } else {
                    echo 'Total: ' . $totalCount . '<br>';
                }
                echo 'Added: ' . $import->addedCount() . '<br>';
                echo 'Updated: ' . $import->updatedCount();
                ?>
            </td>
            <td><?php echo $escape($this->i18n()->dateFormat($job->started())); ?></td>
            
            <td>
            <?php if ($rerunJob) {
                $status = $this->translate('Reran in job ') . $rerunJob->id() . ': ' . $escape($this->i18n()->dateFormat($rerunJob->ended()));
            } else if ($undoJob) {
                $status = $this->translate('Undone in job ') . $undoJob->id() . ': ' . $escape($this->i18n()->dateFormat($undoJob->ended()));
            } else {
                $status = $this->translate($job->status());
            } 
            ?>
            <?php echo $status; ?>
            </td>
            <td><?php echo $this->hyperlink($job->owner()->name(), $this->url('admin/id', array('controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()))); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?php endif; ?>
